# Thresholds for complexity lints
cognitive-complexity-threshold = 30
too-many-arguments-threshold = 8
type-complexity-threshold = 250
too-many-lines-threshold = 150

# Disallow certain patterns
disallowed-names = ["foo", "bar", "baz", "test"]

# Documentation requirements
missing-docs-in-crate-items = true
